<?php
namespace Arshline\Tests\Unit;

use Arshline\Tests\Unit\BaseMonkeyTestCase;
use WP_REST_Request;
use Arshline\Core\Api;
use function Brain\Monkey\Functions\when;

class GuardWhitelistAdditionTest extends BaseMonkeyTestCase
{
    protected function setUp(): void
    {
        parent::setUp();
        when('current_user_can')->justReturn(true);
        when('get_current_user_id')->justReturn(1);
        when('get_option')->alias(function($k,$d=null){
            if ($k==='arshline_settings') return [
                'ai_guard_enabled'=>true,
                'allow_ai_additions'=>false,
                'allow_ai_additions_whitelist'=>['سن'] // allow age field if AI tries to add
            ];
            return $d; });
    }

    private function callPrepare(string $text)
    {
        $req = new WP_REST_Request('POST','/arshline/v1/hoosha/prepare');
        $req->set_body(json_encode(['user_text'=>$text], JSON_UNESCAPED_UNICODE));
        return Api::hoosha_prepare($req);
    }

    public function testWhitelistAllowsAgeField()
    {
        // Baseline 3 fields, expect possible AI attempt to add Age (سن) allowed by whitelist
        $text = "نام شما\nشماره موبایل\nکد ملی\n(شاید لازم باشد سن)";
        $resp = $this->callPrepare($text);
        $this->assertInstanceOf(\WP_REST_Response::class, $resp);
        $data = $resp->get_data();
        $fields = $data['schema']['fields'] ?? [];
        $labels = array_map(fn($f)=>$f['label']??'', $fields);
        $hasAge = (bool)preg_grep('/سن/u', $labels);
        // Age should be present OR guard attempted but removed if pipeline never generated it; ensure note for whitelist if present
        if ($hasAge){
            $notes = $data['notes'] ?? [];
            $this->assertTrue((bool)preg_grep('/guard:ai_allowed_whitelist/',$notes), 'Missing whitelist allowance note for age field');
        } else {
            $this->markTestSkipped('Age field not generated by pipeline; whitelist path not exercised');
        }
    }
}
