name: PHPUnit

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Validate composer.json
        run: composer validate --no-check-publish
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --colors=always
